---
abstract: 'Perl extension to trace subroutine calls'
author:
  - 'JPC, KANE, JV'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Debug-Trace
no_index:
  directory:
    - t
    - inc
requires:
  Data::Dumper: 2.101
version: 0.05
